### ISSUE TITLE
Still getting the Better Wordpress Google XML Sitemaps warning

### ISSUE THREAD

**Issue by dk253** [senlin/so-clean-up-wp-seo#10]
Howdy!  Great plugin idea... but the huge warning keeps coming up.  

I'm running multisite and have activated your plugin on the individual sites.  I just upgraded to the latest version.  I've attached the screenshot.

![yoast warining](https://cloud.githubusercontent.com/assets/6131657/12007579/6d462610-abbf-11e5-9653-2898843c1654.png)

Thanks!

**Comment by senlin** [comment]
Hi, thanks for your question.

The SO Clean Up Yoast SEO plugin does in fact not hide this specific nag. An [earlier issue](https://github.com/senlin/so-clean-up-wp-seo/issues/6) also addressed this already. You can find the answer with the reason why I cannot remove this specific nag so easily here: https://github.com/senlin/so-clean-up-wp-seo/issues/6#issuecomment-142463601

Short version: the class/function that outputs this nag is also used for the OpenGraph warning.

**Comment by dk253** [comment]
Sorry for the dupe!  Thank you very much for your answer and your patience!

**Comment by senlin** [comment]
No worries :)
