### ISSUE TITLE
Hide Gutenberg upsells

### ISSUE THREAD

**Issue by chrisvanpatten** [senlin/so-clean-up-wp-seo#100]
There are a few upsells in the Gutenberg UI which I believe can be hidden.

## Expected behavior
Maybe a new checkbox or option to hide Gutenberg UI upsells.

## Current behavior
n/a

## Possible way to add this
Enqueueing a stylesheet on Gutenberg pages via `enqueue_block_editor_assets` with the following CSS should do the trick:

```css
.yoast div[class^="AnalysisUpsell"] {
  display: none;
}
```

Note that the caret attribute selector is necessary because the full class name is automatically generated (`AnalysisUpsell__Container-sc-1qakqs0-1`) and can't be reliably targeted with a normal class selector.

## Screenshots
<img width="295" alt="Screen Shot 2021-04-23 at 11 04 05 AM" src="https://user-images.githubusercontent.com/1231306/115891048-a1c84780-a423-11eb-9836-61aa583714e0.png">

**Comment by senlin** [comment]
Thanks Chris, will have a look at this soon

**Comment by senlin** [comment]
Hi Chris, apologies I haven't yet addressed this. Looking into it now, but I think things work quite differently now?

![premium-upsell-component](https://user-images.githubusercontent.com/650066/124476443-b7021080-dd9a-11eb-9908-c5dd89ce6005.jpg)

**Comment by senlin** [comment]
Closing due to no further info. Please re-open if there become more details available.
