### ISSUE TITLE
Hide Social Settings 'Unlock with Premium' upsell

### ISSUE THREAD

**Issue by allanrehhoff** [senlin/so-clean-up-wp-seo#101]
## Summary

YOAST Seo has a new unwanted ad for upselling thei rpremium version, (see screenshots section)

This is a well hidden hidden, and not often located ad, but it just seems unproffessional delivering a product containing ads to my clients.

## Steps to reproduce
1. Log in to WordPress
2. Navigate to SEO > Content Types
3. Scroll down to the 'Social Settings' area

## Expected behavior
A feature to hide this button, so clients wont have to see ads in their administration screens.

## Current behavior
An ugly button that doesn't fit the general WordPress UI design standards is showing.

## Possible way to add this
The following CSS snippet should hide it, I'm not sure whether it's best to add it to one of the existing settings, or needs  a new setting in itself.

`.yoast-settings-section.yoast-settings-section-disabled .yoast-settings-section-upsell {display: none;}`

## Screenshots
![2021-06-28_08-55-07](https://user-images.githubusercontent.com/24595705/123593554-ee971880-d7ee-11eb-85d1-2a2e9165a3a4.png)

**Comment by senlin** [comment]
Hi Allan, thank you for your helpful report, I will be adding it to a new version.

**Comment by senlin** [comment]
Hi Allan (@allanrehhoff ),

Looking into this now, but I don't see the social settings area:

<img width="430" alt="Search Appearance - Yoast SEO ‹ WP DEV — WordPress 2021-07-05 14-13-53" src="https://user-images.githubusercontent.com/650066/124477029-7060e600-dd9b-11eb-8d1e-7ccfb7d7a811.png">

**Comment by allanrehhoff** [comment]
Hey Peter 

Are you sure you have the latest version?

I just installed the plugin on another site, and I can still find it.

![Screenshot_20210705-183941](https://user-images.githubusercontent.com/24595705/124500735-92b92a80-ddc0-11eb-8e7c-4fd3e8d3982f.jpg)

- Allan

**Comment by senlin** [comment]
Hi Allan,
Yes I have the latest version. In my test env I only have 2 plugins activated: Yoast SEO and Hide SEO Bloat. Even if I deactivate the latter, I cannot see the social settings. I have filled in a Facebook URL to see if that changes anything, but it doesn't either.
Could it be related to another plugin?

**Comment by senlin** [comment]
Closing due to no further info. Please re-open if there become more details available.
