### ISSUE TITLE
Remove branding from Sitemap

### ISSUE THREAD

**Issue by senlin** [senlin/so-clean-up-wp-seo#109]
Any way to do this with the plugin? 
Remove branding from Sitemap “Generated by Yoast SEO, this is an XML Sitemap”

Original request over at [WP.org](https://wordpress.org/support/topic/remove-branding-from-sitemap/)

## Expected behavior
It can be done and the result will be that the entire first paragraph (first two sentences) will be hidden. The branding-less sentence that indicates the number of sitemaps included can remain. 

## Possible way to add this
body #content > p.expl:nth-of-type(1) {
    display: none;
}

This solution merely hides the paragraph with links from the frontend, it is **not** possible to remove it from the source code.

**Comment by openmindculture** [comment]
So there is still a dofollow link to them in many sitemaps unless we patch the generated `sitemap.xml` or `wp-content/plugins/wordpress-seo/css/main-sitemap.xsl`.

**Comment by senlin** [comment]
It's not a priority issue for me and I already have given the solution, which anyone can add to their admin css.

PRs welcome and I also found a [closed issue](https://github.com/senlin/so-clean-up-wp-seo/issues/32) from the past where I was less inclined to fix it...
