### ISSUE TITLE
Hide content analysis nag by post type

### ISSUE THREAD

**Issue by merchantguru** [senlin/so-clean-up-wp-seo#12]
Some post types I'd like to view the content analysis, and others not. For example, on pages, I use ACF fields for content, and so the Yoast content analysis section is useless. For my "team" post type, I use the regular the_content field, so the content analysis section is useful.

**Comment by senlin** [comment]
Hi Joe, thanks for your feature request.

There actually was [a plugin](https://wordpress.org/plugins/wp-seo-acf-content-analysis/) that enabled the content analysis of ACF fields, but that was before version 3.0 of the Yoast SEO plugin; most likely that is broken now as they issued a warning post about that sometime mid last year.

There seems to be another, but I hear mixed reports, so am not sure whether it works: https://github.com/marcusforsberg/yoast-acf-analysis

Other than that it could be an idea to offer more fine-grained control hiding/showing the content analysis on a per post type basis.

Do you have any ideas on how to integrate that into the plugin? What would in your eyes be a good UI for this? I think we have to bear in mind that some people have heaps and heaps of post types, which can rapidly make things messy.

**Comment by merchantguru** [comment]
I'll definitely check out that new yoast acf plugin b/c that's what I really want - thx for point it out!

For the UI, I would think a multiselect field would be perfect for that section. The WP Migrate plugin has one that works well.

![migrate_db_pro_ _wp_performance_pro_ _wordpress](https://cloud.githubusercontent.com/assets/658245/13433931/e344c842-df88-11e5-8b96-08eea8b89618.png)

Here's a link to [the code on GitHub](https://github.com/deliciousbrains/wp-migrate-db/blob/master/template/common/compatibility.php)

**Comment by senlin** [comment]
Hi Joe,

Thanks for the comments and suggestion. 

If team Yoast indeed is taking over the development of the content analysis, then I think that is a much better solution, than for my plugin to add it in. What I mean is Joost's fork is of much more value to his plugin. I therefore propose to shelve your request for the moment and first see where the fork is going. Is that okay with you? 

My line of thought is that ultimately my plugin should not even have to exist. 
Your 2nd message therefore is very welcome news indeed as it seems that Mr. de Valk is finally opening up. Of course we should not applaud too fast as it clearly says "Temporarily disabled", but it definitely is a step in the right direction :)

I will therefore adjust my plugin accordingly and try to release a new version today.

**Comment by merchantguru** [comment]
No problem - if that forked acf content plugin or Yoast's eventually analyzes acf content, then usually that's all that need as the cpt's should use Yoast's SEO content analysis. The only exception might be non-public cpts which wouldn't need SEO analysis... but those aren't common.

As for whether you're plugin will ever be irrelevant, I don't believe so. See:
https://twitter.com/MerchantGuru/status/704775357501542400

**Comment by senlin** [comment]
Hi Joe, thank for the link, interesting. I no longer participate in any conversations with Mr de Valk as he likes to twist things around and pulls things out of context. 
So yes you're right, the plugin will probably have to exist for a long time to come :) I will just have to try to keep up with any changes.

**Comment by merchantguru** [comment]
cool. ok - will close this ticket then. thnx for the discussion!
