### ISSUE TITLE
Ad in page markup

### ISSUE THREAD

**Issue by tbnv** [senlin/so-clean-up-wp-seo#14]
Hello,

Do you take the comment tags that the SEO plugin adds in the markup into account? I still can see
`<!-- This site is optimized with the Yoast SEO plugin v3.2.3 - https://yoast.com/wordpress/plugins/seo/ -->`
and
`<!-- / Yoast SEO plugin. -->`

**Comment by senlin** [comment]
Yeah, we're not going to do anything about that, that has nothing to do with the nags in the WordPress Dashboard.
