### ISSUE TITLE
can't update plugin

### ISSUE THREAD

**Issue by biggens55** [senlin/so-clean-up-wp-seo#20]
my sftp uses port 22 but you seem to default to port 21. how can I update 

using 2.4.0

**Comment by senlin** [comment]
Hi, you should be able to update the plugin from with the WP Dashboard, no need for (S)FTP. But in case you want to use (S)FTP, you should be able to do that too. In that case it is probably better to first delete the plugin and then upload it again.
Either way, this actually does not have anything to do with the plugin...
