### ISSUE TITLE
All SEO Scores

### ISSUE THREAD

**Issue by lancem631** [senlin/so-clean-up-wp-seo#21]
Installed your plugin Version 2.5.4 on WP 4.7 hoping to hide 'All SEO Scores' dropdown on Posts admin backend.  So far no effect.  Please advise fix.  Thank you.

**Comment by senlin** [comment]
Apologies for the late response, for some reason I did not get notified...

If you still have the issue, can you please add a screenshot to clarify?

**Comment by soaro77** [comment]
He is talking about the All SEO Scores dropdown on the All Posts admin page. It's ID is wpseo-filter.

**Comment by senlin** [comment]
Thanks for clarifying that @soaro77 
I don't think this falls under the "bloat" the plugin tries to hide.
