### ISSUE TITLE
New SEO Column on Posts Page

### ISSUE THREAD

**Issue by soaro77** [senlin/so-clean-up-wp-seo#23]
It appears Yoast has added a new column called Readability to the posts page. I modified the source in my site to get rid of it but thought you might also be interested in the modification I made. I didn't know if you had developers for the code or if anyone could so I'm posting this as an issue. It probably should be added as a separate item in the settings but I just wanted it gone.

In the page, so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php at current line 230 under comment // all columns I replaced the line with this:
echo '.column-wpseo-score,.column-wpseo_score,.column-wpseo-score-readability,.column-wpseo-title,.column-wpseo-metadesc,.column-wpseo-focuskw{display:none;}'; // @since v2.0.0 remove seo columns one by one

Then after line 235 under comment // seo score column I added this line:
echo '.column-wpseo-score-readability{display:none;}'; // @since v2.0.0 remove seo columns one by one

**Comment by senlin** [comment]
Hi @soaro77 
Thanks for catching this, it indeed seems there is yet another column!
In the upcoming version we will add an option to remove it.
In the meantime your enhancement will work.
I will update this thread once I have released the new version.
Thanks,
Piet

**Comment by senlin** [comment]
Just released the new version that addresses this issue and a bunch of others. Thanks again for your input, Curtis!
