### ISSUE TITLE
Yoast admin bar icon exists in Network Admin

### ISSUE THREAD

**Issue by afragen** [senlin/so-clean-up-wp-seo#26]
I know there's now a setting inside Yoast to remove the Yoast icon from the admin bar. However, this is only accessible from an individual sites Yoast settings and not from the Yoast network settings.

Can we bring back the setting for removing this so it works for the Network Admin too?

**Comment by senlin** [comment]
Hi Andy, thanks for all your PRs and input. 

As far as I remember my plugin never had a setting that removes the entire drop down menu and icon. We did have a setting that removes some items from it, can't find it at the moment.

I don't mind adding it now, we can use the same explanation we use on other options:
_Although it can be easily dismissed on a per user basis, this setting hides the Adminbar menu globally._

**Comment by senlin** [comment]
Looks like PHPStorm is very strict :)

**Comment by senlin** [comment]
Found a small issue with the readability column setting. 

Although the column does not show in the Edit Posts/Pages screens (as per the default setting), for some reason the box has not been ticked. Please see attached screenshot.

![so_hide_seo_bloat_settings_ _testbed_ _wordpress](https://cloud.githubusercontent.com/assets/650066/24653604/fd8caac6-1925-11e7-96c2-179a6fb8b955.png)

**Comment by afragen** [comment]
How do you wish to proceed? It's only global from admin or super admin making it so. Clearly leaving it unchecked still allows individual site admins to remove via Yoast's settings. Yoast removes the entire menu too.

**Comment by senlin** [comment]
No it is fine, the setting in Yoast indeed also removes the entire thing. I did not remember that we once had it. Sorry for the misunderstanding.
