### ISSUE TITLE
Error loading scripts

### ISSUE THREAD

**Issue by jawittdesigns** [senlin/so-clean-up-wp-seo#3]
OK, so there seems to be something pretty weird going on. I don't know if it's a conflict with another plugin or just an issue with this one. 

I'm getting the error because when SO Clean UP WP SEO is active, something is trying to load scripts that don't exist?

here an example of the error
```http://cjhs2.dev/wp-includes/js/tinymce/plugins/codepress-admin-columns/codepress-admin-columns.php/plugin.min.js?wp-mce-4109-20150505 ```

This error is happening for every active plugin on the site. It seems to be only happening on the 1.6 version. I have another site with this plugin with version 1.5  and there are no errors.

**Comment by senlin** [comment]
Thanks for reporting this issue @jawittdesigns we will look into it (try to duplicate it) and report back to you. The only thing we changed on v1.6 is added a nag id to the css, but we'll see.

**Comment by senlin** [comment]
We cannot reproduce this issue.

Dumb question: do you have Yoast SEO installed **and** are you on a multisite install?

As you can see from the [commit](https://github.com/senlin/so-clean-up-wp-seo/commit/91a4a20e68277a5810044a6caf7ab3b1e8204684#diff-9c84d77f53ff45cbe56815ae4e44657d), literally the only thing that changed between v1.5 and v1.6 was the addition of `, #wpseo-dismiss-gsc` on line 129

Please check again your install where the conflict could be as we would like to know if our plugin causes a conflict with another one.

**Comment by jawittdesigns** [comment]
I nailed down the issue. It wan't a plugin , but some code I have for disabling the (yuck) emojis. The issue was being caused because I was was running a method with add_filter through an add_action('init). It seemed to create some type of weird loop with all the plugins.

Why your plugin was the trigger for this? I'm not sure. Here's a gist of the code. If you want to try and debug it.
https://gist.github.com/wpgaijin/e1b62eb09731362397f1

**Comment by senlin** [comment]
Hi Jason, thanks for checking and glad to hear that it wasn't my plugin.

The plugin does hook into the `admin_init`[here](https://github.com/senlin/so-clean-up-wp-seo/blob/master/so-clean-up-wp-seo.php#L111).

Maybe disable the emojis in a different way? I'm using [this function](https://github.com/senlin/Code-Snippets/blob/master/Functions/Admin-Dashboard/remove-emojis.php) and just tested this on a clean dev site with 2015 theme, my SO Clean Up Yoast SEO plugin and this function and again I am not able to reproduce the error you described above.
