### ISSUE TITLE
PHP Warning:  in_array() expects parameter 2 to be array

### ISSUE THREAD

**Issue by burkeallen** [senlin/so-clean-up-wp-seo#30]
We are getting the following errors when this plugin is activated

PHP Warning:  in_array() expects parameter 2 to be array, boolean given in wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php on line 247
PHP Warning:  in_array() expects parameter 2 to be array, boolean given in wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php on line 251
PHP Warning:  in_array() expects parameter 2 to be array, boolean given in wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php on line 254
PHP Warning:  in_array() expects parameter 2 to be array, boolean given in wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php on line 258
PHP Warning:  in_array() expects parameter 2 to be array, boolean given in wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php on line 262
PHP Warning:  in_array() expects parameter 2 to be array, boolean given in wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo.php on line 266

WP Version: 4.7.3
PHP Version: 7.0.17
Database Version: 5.5.54
ubuntu 14.04.1
Yoast - Version 4.5 
SO Hide SEO Bloat Version 2.6.1

**Comment by senlin** [comment]
@burkeallen 
Hi, thanks for reporting this, it is related to issue #24 where we're working on.

Fortunately a PHP Warning is not an Error, and the Warning only shows with `WP_DEBUG` set to `true` or when notices, warnings and error are logged in a debug file.

You can solve the issue by re-setting the the checkboxes for the admin columns.

I will close this issue now and you can follow the progress on #24 

Apologies for the inconvenience.

**Comment by burkeallen** [comment]
Thank you,

I will follow the instructions to remove this warning


*Burke Allen*
*NovoLogic, Inc*
*mobile 770-265-4362 *

**Comment by senlin** [comment]
@burkeallen 
We just released [version 3.0.0](https://github.com/senlin/so-clean-up-wp-seo/releases/tag/v3.0.0) which fixes this issue.
