### ISSUE TITLE
Remove Yoast Comments from Source Code

### ISSUE THREAD

**Issue by VinceZaZa** [senlin/so-clean-up-wp-seo#31]
This is a feature request:

You have come this far - how about going to the next step and having the option to remove the HTML comments that identify Yoast SEO plugin in the source code.

Option to remove the URL at the top of the sitemap.xml

Thank you

**Comment by senlin** [comment]
Hi Vince,
Thanks for your feature request.
What is the reason you would want these comments gone? Without them it is still very easy to see which plugin adds the code to the source.

**Comment by VinceZaZa** [comment]
Hi Piet,
You are right, it is still easy to find which plugin is being used. However, to the casual observer, clients etc it is not so easy or rather not so obvious.
There is already a plugin - 'Remove Yoast SEO comments' https://en-gb.wordpress.org/plugins/remove-yoast-seo-comments/ that does this reasonably well.  However, it means another plugin that must be added. I think having it all in one place would be a good idea.

There are several pieces of code floating around the web that can also do the trick - but again, they are seldom updated so impossible to use.

**Comment by senlin** [comment]
Hi Vince,
The description of the Hide SEO Bloat plugin is

> Clean up several unwanted things that the Yoast SEO plugin adds to your WordPress Dashboard

The imperative word here is **WordPress Dashboard**

The source code is not the dashboard and as such I am not inclined to add this to the plugin. As there is already a plugin that is being kept up to date, it would not make sense to re-invent the wheel. 

I get it that you don't want to install 2 extra plugins to get rid of the crap the Yoast plugin adds, but ultimately it is your choice to install Yoast in the first place. There are plenty alternatives, which are also excellent. A very good example is [The SEO Framework](https://theseoframework.com/). This plugin also adds comments to the source code, but it has a filter in place that you can use to stop that.

**Comment by VinceZaZa** [comment]
"I get it that you don't want to install 2 extra plugins to get rid of the crap the Yoast plugin adds"

Ditto that

**Comment by senlin** [comment]
@VinceZaZa - you'll be happy to know that with the release of v3.11.0 this issue is finally taken care of :)
