### ISSUE TITLE
[Request] Remove sitemap generated by Yoast

### ISSUE THREAD

**Issue by Tarun80** [senlin/so-clean-up-wp-seo#32]
Hello,

I was hoping that an option can be added to remove the following:

> Generated by Yoast SEO, this is an XML Sitemap, meant for consumption by search engines.
> You can find more information about XML sitemaps on sitemaps.org

As php/html code:
```html
Generated by <a href="https://yoast.com/">Yoast</a> <a href="https://yoast.com/wordpress/plugins/seo/">SEO</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>
				You can find more information about XML sitemaps on <a href="http://sitemaps.org">sitemaps.org</a>```

It can be found in ```wordpress-seo\css\xml-sitemap-xsl.php``` and the lines are 93-96.

**Comment by senlin** [comment]
Hi @Tarun80 

This has been asked before over at the [WP Forums](https://wordpress.org/support/topic/please-add-2/)

The explanation is that the description of the Hide SEO Bloat plugin is

> Clean up several unwanted things that the Yoast SEO plugin adds to your WordPress Dashboard

The imperative word here is **WordPress Dashboard**

I will keep this issue open for now, to see if there are more people that would want to see this added to the plugin.

You're always welcome to send me a PR (or message) with a way to remove it :)

**Comment by Tarun80** [comment]
I generally manually remove it by editing the file after updating. Not sure how to add it to your wonderful plugin.

**Comment by senlin** [comment]
Yeah manually editing the file is not sustainable :)
Looking at [the file](https://github.com/Yoast/wordpress-seo/blob/856b147ad798a1e5dec08b7cdcad8f5ed62b8741/css/xml-sitemap-xsl.php), I don't think it will be that easy to hide any of that (removing is not possible) as all content seems to be output by XSL.

**Comment by senlin** [comment]
With the [latest version](https://github.com/Yoast/wordpress-seo/blob/release/5.1/readme.txt#L138) (of Yoast SEO) it now seems possible to add sitemaps from other plugin. 

Does that solve this issue?

**Comment by senlin** [comment]
closing due to no replies
