### ISSUE TITLE
Where is the hide expired / invalid license nag?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [senlin/so-clean-up-wp-seo#33]
Cpt. Obvious is sure to say something like "Just buy a license bro". Though, other's could be wondering... _How do I remove the expired / invalid license nag?_

![insane amount of notification nags](https://cloud.githubusercontent.com/assets/1291364/25875875/d90c41b0-34e7-11e7-8746-386631bfc839.png)

I recommend adding an option to remove expired / invalid license nag. You can cut (or delete) a small snippet of code from local file:

`\wordpress-seo-premium\vendor\yoast\license-manager\class-license-manager.php`

before uploading it to remote location:

`/public_html/wp-content/plugins/wordpress-seo-premium/vendor/yoast/license-manager/class-license-manager.php`

Specifically, you'll want to remove lines `117 thru 119`

```
<div class="notice notice-error yoast-notice-error">
    <p><?php printf( __( $message, $this->product->get_text_domain() ), $this->product->get_item_name(), $this->product->get_license_page_url(), $this->product->get_tracking_url( 'activate-license-notice' ) ); ?></p>
</div>
```

![This is how you delete and remove the license nag](http://i.imgur.com/4aXYM80.gif)

**Comment by afragen** [comment]
@grand-lotus-iroh you have premium Yoast plugins installed and Yoast is rightfully asking for a license key. Why would we block that? Just enter the license key.

Deleting code from the Yoast plugin is not how this plugin functions.

**Comment by senlin** [comment]
@grand-lotus-iroh 
I agree with @afragen the Hide SEO Bloat plugin is to hide/remove the bloat from the free version of the Yoast SEO plugin. If you choose to buy into the premium version, then (obviously) you need a license key.
