### ISSUE TITLE
when multiple settings can be selected, options are not saved and therefore not output

### ISSUE THREAD

**Issue by senlin** [senlin/so-clean-up-wp-seo#34]
@afragen 
I noticed a problem with the current version of the plugin.
Everywhere where there are multiple settings can be selected:
- Problems/Notifications
- Content (Readability) / Keyword (SEO) Score
- Help center
- Admin columns

Although it looks like the settings are saved on the Settings page, the relevant styling rules are in fact not added to the `cuws_settings` options table.

Do you have any idea why/how that is possible?

Thanks for having a look at it!

**Comment by afragen** [comment]
I'll take a look taker today. I seem to recall that working. Is there something specific that your testing? What do you see and what do you expect to see?

**Comment by senlin** [comment]
Nothing specific I'm testing. I noticed an update of Yoast, so I checked whether everything was still working or whether they added new bloat.

Then I realised that none of the 4 above mentioned settings are actually "set", except on the Settings page.

Example:
When I check boxes of Help Center Setting for both "Hide ad for premium version" and "Hide the entire help center", like:
![so_hide_seo_bloat_settings_ _wp_dev_ _wordpress](https://cloud.githubusercontent.com/assets/650066/26521969/d9103174-42e5-11e7-9b07-48af59da1170.png)

I expect on the Yoast Dashboard that the entire Help Center is gone, but it is still there:
![general_-_yoast_seo_ _wp_dev_ _wordpress](https://cloud.githubusercontent.com/assets/650066/26521975/f46bb7ea-42e5-11e7-9661-848fbc001711.png)

The same goes for all 4 of the above mentioned settings.

**Comment by senlin** [comment]
Also when you have a look at the stylesheet that is loaded on the admin pages, the styles of those 4 settings are not added to it.

**Comment by afragen** [comment]
I took a look on my test site and was able to test the admin columns setting. I initially only saw 2 of the extra columns, SEO and Readability, but the did individually hide when selected.

**Comment by senlin** [comment]
The admin columns can have something to do with what you set earlier in screen options. Is it possible for you to check with the help center example I gave above? And preferably on a live site?

**Comment by afragen** [comment]
I tested the help center hiding and it also worked as expected, hiding on the edit posts/pages page and on the Yoast settings page.

**Comment by afragen** [comment]
The admin columns is strange in that hiding from the plugin results in a unchecking in the screen options, but unchecking the plugin option doesn't seem to reverse this.

**Comment by senlin** [comment]
> This on my test site.

Is that a local environment or a staging server?

> but unchecking the plugin option doesn't seem to reverse this.

And you have not previously set anything in the screen options?

**Comment by afragen** [comment]
It's on a staging server.

I rechecked all the screen options, some didn't come back.

**Comment by senlin** [comment]
I have no idea what is going on on my local and staging sites :(
But after wiping them both and starting over from scratch, settings seem to show again.

The only problem that I also can confirm is with the admin columns.
I actually would like it when we remove the option entirely and only make it an option to show or hide the focus keyword. What do you think of that?

**Comment by afragen** [comment]
Sounds fine. I leave the showing/hiding to you. 😉

**Comment by senlin** [comment]
Sorry for the false alarm and have a great weekend!
