### ISSUE TITLE
Multisite Support?

### ISSUE THREAD

**Issue by MarcWoodyard** [senlin/so-clean-up-wp-seo#4]
I just network activated the plugin on my multisite network, but the Yoast SEO dasbhoard messages are still there. Is this normal?

Thanks, 
Marc

<img width="819" alt="wordpress-seo-dashboard-messages" src="https://cloud.githubusercontent.com/assets/5026965/9205440/172403a6-4017-11e5-9874-0270f78c30c1.PNG">

**Comment by senlin** [comment]
Thanks for reporting this, tbh we had not yet tested it on Multisite. We will add this to our todo list and in the meantime you can use the plugin on Multisite if you activate it on a per-site basis.
Apologies for any inconvenience.

**Comment by ModMarc** [comment]
Looking forward to the update. Thanks for the help!

**Comment by senlin** [comment]
With the release of version 2.0.0 when you network activate the plugin you need to go to the individual settings pages and save them. When you activate the plugin per site you don't need to do anything, unless of course you want to change the default settings.
