### ISSUE TITLE
[feature request] remove SEO filters on main edit Post/Page screen

### ISSUE THREAD

**Issue by caban13** [senlin/so-clean-up-wp-seo#43]
I want to remove to two select boxes that appear in every admin page listing post, pages or cpts:

* SEO Scores filter dropdown
* Readability Scores filter dropdown

Here is an image: https://snag.gy/SJLExf.jpg

I was unable to un-hook, so I hide them. In my functions.php I have:
```
function my_hide_wpseo() {
    if ( is_admin() ) {
	print '<style>select#wpseo-filter, select#wpseo-readability-filter {display:none;}</style>';
    }
}
add_action( 'restrict_manage_posts', 'my_hide_wpseo', 15 );
```
I hope this explains.

**Comment by senlin** [comment]
It already is possible within the General settings of Yoast SEO under the Features tab to turn the SEO Scores and/or Readbility Scores on or off, but that is global.

@caban13 wants to be able to have them turned on, but remove/hide them from the Edit Post/Page/CPT screens.

Anyone who also would like this, please vote it up. 10 votes or more we will consider it, 25 votes or more we will implement it.
