### ISSUE TITLE
Feature Request: Hide Upsell after Post Deletion

### ISSUE THREAD

**Issue by mrwweb** [senlin/so-clean-up-wp-seo#44]
Yoast's plugin recently started trying to upsell at the top of the All Posts screen every time you delete a post (page, anything). Super annoying. Would love to see that hidden!

**Comment by mrwweb** [comment]
screenshot:

![image](https://user-images.githubusercontent.com/1238696/45845859-220df580-bcdb-11e8-9994-63963bd55a9a.png)

**Comment by senlin** [comment]
hi @mrwweb - thanks for the report.

That is just crazy! Will definitely get rid of that soon! Thanks for the screenshot to visualise the issue.

**Comment by senlin** [comment]
Hmmm, this is going to be more difficult than I had hoped :(

The notice has very generic classes: `yoast-alert notice notice-warning is-dismissible`, so there is a risk that if I do a `display: none;` on that, other things will not be displayed either.

This file is responsible for adding the actions: https://github.com/Yoast/wordpress-seo/blob/trunk/admin/watchers/class-slug-change-watcher.php#L26-L33

If anyone has an idea on how to disable this, input is much appreciated!

**Comment by mrwweb** [comment]
It looks to me like that whole file is only there for the purpose of the upsells, so could you just remove the actions wholesale?

**Comment by senlin** [comment]
Yeah, unfortunately it's not as easy as that.

**Comment by senlin** [comment]
@mrwweb you can find the new release at https://github.com/senlin/so-clean-up-wp-seo/releases/tag/v3.8.0 and soon it will be available on the WP Plugins Directory. Keep in mind to check the Settings page to tick the new option box.

**Comment by mrwweb** [comment]
FYI: I can confirm that the ads no longer appear.

However, I didn't need to check the box in settings nor did I save the settings yet. The following notice is on the settings page:

> Notice: Undefined index: hide_post_deletion_premium_ad on wp-content/plugins/so-clean-up-wp-seo/admin/class-so-clean-up-wp-seo-admin-api.php:58

I don't have time to go digging, but you likely need to implement a default value for each option with something like `if( isset( $option_value ) { ...`

**Comment by senlin** [comment]
Hmmm, thing is we do set default values already at https://github.com/senlin/so-clean-up-wp-seo/blob/develop/includes/class-so-clean-up-wp-seo.php#L425-L455

@afragen - do you happen to know what's going on with this?

**Comment by afragen** [comment]
I’m away until next week, but I’ll take a look when I get back.

**Comment by afragen** [comment]
Might need to activate and deactivate the plugin as the defaults only seem to be set during activation. Since then default wasn’t previously present you get an error. Just running the code in my head as I don’t have a laptop with me.

**Comment by senlin** [comment]
If that is indeed how it works, then we might need to rethink that as that is not very user friendly.

**Comment by afragen** [comment]
The PHP warning is only a warning. Just put in the changes that a deactivation/deactivation is needed. 

Otherwise you’ll need to write an update procedure to ensure any empty settings are filled.

**Comment by mrwweb** [comment]
Seems like it may be worth redoing how options are handled in this plugin. The general best practice I know and has served me well is to:

1. Only save options to the database that the user has explicitly set
2. Provide default values for all options (but don't save them to the DB)
3. Save all plugin options in a single option as an array

So in the plugin you handle defaults and avoid warnings is something like this:

```php
<?php
// get the option, set empty array as default value if there's nothing there
$my_plugin_options = get_option( 'my_plugin_options', array() );
// check if a specific option exists, use it if so. set false (or whatever) as default otherwise
$my_plugin_option = isset( $my_plugin_options['a_specific_option'] ) ? $my_plugin_options['a_specific_option'] : false;
// ... do stuff with $my_plugin_options['a_specific_option'] now
```

You could obviously abstract that pattern to a function to speed things up or make a merged array of defaults and user-set options early on, but that's just different implementations of the same best practice.

**Comment by senlin** [comment]
@mrwweb - Thanks for your thoughts and input Mark.

> Only save options to the database that the user has explicitly set

Regarding this the idea behind the plugin is that people install it to clear up the mess, so instead having the user tick 20 boxes, the default setting is that almost everything is checked.

Of course I am happy to be persuaded otherwise if it turns out that it simply works easier to have them set by the user. In that case adding a new option would also mean that the user has to revisit the settings?

**Comment by afragen** [comment]
Perhaps a simple

`array_merge( $this->get_defaults(), $this->options );`

At the end of the CUWS constructor.

**Comment by senlin** [comment]
New version just has been released on the WP Plugins Directory too.

Thanks for all your help!
