### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by jaycollier** [senlin/so-clean-up-wp-seo#46]
I have the plugin installed on Multisite. However, the Yoast box still appears on custom post type write screens. Is there something that needs to be done to activate the plugin on CPTs?

**Comment by senlin** [comment]
Hi Jay, thanks for reporting this.

It should work normally on CPTs. Which box still appears? Can you send a screenshot? Have you selected the option on the settings page and saved them?

**Comment by jaycollier** [comment]
Thanks for responding so quickly.

On the network settings page — linked from the Network Plugin's list — I don't see any reference to CPTs. In any case, I checked every single box.

On the CPT edit page (which was created with Pods), I still see the meta box.

![screen shot 2018-09-25 at 8 56 25 am](https://user-images.githubusercontent.com/1320213/46015716-fc993700-c0a0-11e8-9ff6-47b89767f09d.png)

![screen shot 2018-09-25 at 8 57 51 am](https://user-images.githubusercontent.com/1320213/46015842-4550f000-c0a1-11e8-9433-8660ed77389c.png)

**Comment by senlin** [comment]
Ah okay, now it is clearer what you mean.

The plugin does not remove the entire Yoast SEO metabox, as that would mean that it would become completely unusable. The purpose of our plugin is to remove the bloat: all the cartoon ads and nags.

It is possible in the settings of the Yoast SEO plugin to select on which post types the metabox shows. To do so go to Yoast SEO > Search Appearance and select for which post type you would like to show/hide the metabox.

<img width="423" alt="search appearance - yoast seo wp dev wordpress-180925" src="https://user-images.githubusercontent.com/650066/46016754-83640900-c0cd-11e8-9f6c-d79ce13a73d6.png">

**Comment by jaycollier** [comment]
Thank you! You answered my question, and this issue is resolved.
