### ISSUE TITLE
Feature Request: Hide premium ad in gutenberg.

### ISSUE THREAD

**Issue by allanrehhoff** [senlin/so-clean-up-wp-seo#53]
With the release of gutenberg in wordpress 5.0 Yoast SEO has made compatibility changes on their part.
This includes the mandatory ad to buy the premium version.

I suggest a feature to hide this ad, or simply extend the 'Hides the "Premium" submenu in its entirety.' setting.

Screenshots attached for clarity

![2018-12-13_09-09-51](https://user-images.githubusercontent.com/24595705/49925289-bb9f0a80-feb8-11e8-83a4-cfddc3883b7a.png)
.

**Comment by senlin** [comment]
Hi Allan,
Thank you for sending this feature request including screenshot for clarification.
I was on a short holiday when WP 5.0 dropped so did not have a chance to see this yet. Will work on it soon and update this ticket when the new version is released.
Cheers,
Pieter

**Comment by senlin** [comment]
Apologies for the delay, looking into this now.

Unfortunately the suggestion you did doesn't do anything.

It seems to be hooked into a [`edit-post-pinned-plugins`-class](https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/header/pinned-plugins/index.js#L16-L18) that comes with the new editor and is filled with javascript.

If anyone knows how to remove this, feel free to go ahead and do a PR as I will not be able to remove this.

**Comment by senlin** [comment]
As there doesn't seem to be an easy solution, I'm closing this now. Feel free to re-open it if you have new ideas on how to implement it.

**Comment by Dibbyo456** [comment]
> As there doesn't seem to be an easy solution, I'm closing this now. Feel free to re-open it if you have new ideas on how to implement it.

Indeed, you are right. At first I thought remove some hooks might do the trick but nope. Nothing filterable found. Then I thought of CSS patch because if anything does not work CSS patch will, but nope..! That does not work either because there is no unique css in that particular nag.

Yoast really pissed me off. There is almost no way to do it without modifying core files.
Thankfully I don't use Gutenberg because it's a complete disaster, so not gonna waste time on this one.

**Comment by senlin** [comment]
> Thankfully I don't use Gutenberg because it's a complete disaster

I hear you! The first plugin that I install on new sites is my own [Classic Editor Addon](https://github.com/senlin/classic-editor-addon).
