### ISSUE TITLE
Yet another Yoast column to hide --- column-wpseo-links

### ISSUE THREAD

**Issue by anton-vrba** [senlin/so-clean-up-wp-seo#55]
Hi, there is another yoast column which I hid successfully by by including the line "echo '.column-wpseo-links{display:none;}';" after line 309 in class-so-clean-up-wp-seo.php.   Possibly you can extend your settings to include this column as well

Thanks
Anton
-----------

<th scope="col" id="wpseo-links" class="manage-column column-wpseo-links sortable desc"><a href="https://xxxxxxxxx.com/wp-admin/edit.php?orderby=wpseo-links&amp;order=asc" class="yoast-tooltip yoast-tooltip-n yoast-tooltip-multiline" aria-label="Number of internal links in this post. See &quot;Yoast Columns&quot; text in the help tab for more info."><span><span class="yoast-linked-to yoast-column-header-has-tooltip" data-label="Number of internal links in this post. See &quot;Yoast Columns&quot; text in the help tab for more info."><span class="screen-reader-text"># links in post</span></span></span><span class="sorting-indicator"></span></a></th>

**Comment by senlin** [comment]
@anton-vrba 

Hi Anton, thanks for your suggestion. I haven't had much time to update the plugin lately, but I welcome any PRs :)

Cheers!

**Comment by senlin** [comment]
Hi Anton, I'm looking at this issue at the moment on a vanilla install, but cannot see the column.

Could you please make a screenshot available?

**Comment by anton-vrba** [comment]
Hi Peter

here it is, far right of admin menu Posts>AllPosts



------ Original Message ------

**Comment by anton-vrba** [comment]
Hi Peter here it is,  far right of Admin Menu Posts?AllPosts



Subject: Re: [senlin/so-clean-up-wp-seo] Yet another Yoast column to 
hide --- column-wpseo-links (#55)

**Comment by senlin** [comment]
Thanks for the screenshot, will fix that in the upcoming .1 release

**Comment by senlin** [comment]
@anton-vrba thanks for your patience, I have just released the version that hides this column too. You will see the new checkbox on the Settings page.
