### ISSUE TITLE
Get premium nag in the Yoast metabox

### ISSUE THREAD

**Issue by ghost** [senlin/so-clean-up-wp-seo#59]
Open a post, check the Yoast meta box below the post and just below focus keyword, check for this box http://prntscr.com/np4i4i.

**Comment by senlin** [comment]
I had a look at this, but there are no classes added to this notice, so I cannot just simply hide it as it will also hide other, maybe important, notices.

Most likely this needs to be done programmatically, but I haven't figured out a way to do that yet. Any input welcome.

The code on Yoast SEO is as follows.

File: `wordpress-seo/admin/class-admin-init.php L52`:
`add_action( 'admin_notices', array( $this, 'permalink_settings_notice' ) );`

Same file `L724-739`:
```
	/**
	 * Shows a notice on the permalink settings page.
	 */
	public function permalink_settings_notice() {
		global $pagenow;

		if ( $pagenow === 'options-permalink.php' ) {
			$warning = esc_html__( 'WARNING:', 'wordpress-seo' );
			/* translators: %1$s and %2$s expand to <i> items to emphasize the word in the middle. */
			$message = esc_html__( 'Changing your permalinks settings can seriously impact your search engine visibility. It should almost %1$s never %2$s be done on a live website.', 'wordpress-seo' );
			$link    = esc_html__( 'Learn about why permalinks are important for SEO.', 'wordpress-seo' );
			$url     = WPSEO_Shortlinker::get( 'https://yoa.st/why-permalinks/' );

			echo '<div class="notice notice-warning"><p><strong>' . $warning . '</strong><br>' . sprintf( $message, '<i>', '</i>' ) . '<br><a href="' . $url . '" target="_blank">' . $link . '</a></p></div>';
		}
	}
```

PR welcome!

**Comment by senlin** [comment]
Thanks will add this to the todo list

**Comment by senlin** [comment]
this does not seem to be an issue anymore and OP's account has been removed, so closing this
