### ISSUE TITLE
Yoast SEO/Google XML Sitemaps nag

### ISSUE THREAD

**Issue by dycweb** [senlin/so-clean-up-wp-seo#6]
Hi. I'm hoping you could add support in your plugin for the Yoast SEO conflict nag for Google XML Sitemaps plugin. This one is annoyingly pervasive. *It appears on every page in the back end for ALL user levels even after being dismissed.* It's very confusing to my contributors because they don't understand what it means and can't access plugins. A plea to Yoast has been ignored because I am not a paying customer (I use the free version of Yoast SEO). 

![yoast](https://cloud.githubusercontent.com/assets/14283053/9886769/fa583e9a-5bb9-11e5-9e0d-10679b02daa0.png)

At this point, the nag has annoyed me to the point where I would never use Yoast's version of an XML sitemap even if it was better. For now, I have hidden the warning message by adding the following to my current theme's functions.php file but this is just a temporary fix and I don't feel like I should have to put a child theme in place just for this.

    add_action('admin_head', 'disable_yoast_notice');

    function disable_yoast_notice() {
      echo '<style>
        #wpseo-dismiss-plugin-conflict {
         display: none;
        }
      </style>';
    }

Thanks for your help. :)
April

More info:
https://wordpress.org/support/topic/warning-the-google-xml-sitemaps-plugins-warning-not-resolved
https://wordpress.org/support/topic/garbage-error-message
https://wordpress.org/support/topic/problem-with-google-xml-sitemap-plugin-2
https://wordpress.org/support/topic/xmlsitemaps-warning
https://github.com/Yoast/wordpress-seo/issues/2329 (fix requested almost 5 months ago)

**Comment by senlin** [comment]
Hi April,

Thanks for your request.

Although I understand the problem, I don't think that the SO Clean Up Yoast SEO plugin is a good vehicle to solve the issue. The reason is that the nag only appears when 2 plugins are at play.

I would therefore suggest to keep using your own fix or to release it as a plugin yourself perhaps?

**Comment by senlin** [comment]
Can you by the way let me know which Sitemap plugin it is exactly? There are quite a few of them and the *Google XML Sitemap* hasn't been updated in 3 years...

**Comment by dycweb** [comment]
My apologies for the delay in answering your question. The plugin I'm using is https://wordpress.org/plugins/google-sitemap-generator/ and it seems to have been updated earlier this year and several times in 2014.

I suspect the nag appears whenever any other plugin that generates an XML sitemap for Google is installed. The problem is that the nag appears continuously even when you've elected not to use Yoast's version. I can understand showing the message once or twice to admins for notification purposes but after that it becomes super annoying and, as far as I can tell, the only way to dismiss the notice permanently is to actually use Yoast's version. I dislike being manipulated in that way and would not now use it even if were a better product.

I understand that you can't add it to SO Clean Up Yoast SEO. I'll just have to keep trying to get Yoast to fix it. I'm glad to have discovered your plugin anyway! Thanks for your response.

Regards,
April

**Comment by senlin** [comment]
Thanks for your reply April.

I installed the plugin to see what happens. Quite a bizarre warning indeed. I cannot check whether it indeed keeps popping up after dismissing it, but I believe you immediately as that is the exact same with the other nags and "warnings".

It is fairly easy to completely get rid of that warning once and for all. But the problem with this is that Yoast SEO has a whole list of potentially conflicting plugins. If I were to hide this box, then it also is hidden in some more legitimate cases.

You can see the list of potential conflicting plugins in the file [`wordpress-seo/admin/class-plugin-conflict.php`](https://github.com/Yoast/wordpress-seo/blob/trunk/admin/class-plugin-conflict.php#L19-L96).

The warning sits in a div like this:
`<div data-json="{&quot;section&quot;:&quot;xml_sitemaps&quot;,&quot;plugins&quot;:[&quot;google-sitemap-generator\/sitemap.php&quot;]}" data-nonce="ea64652a52" id="wpseo-dismiss-plugin-conflict" class="yoast-notice notice is-dismissible error yoast-dismissible">`
So you can see that the conflicting plugin in this case is *google-sitemap-generator*, but that data is pulled from a json string and I don't know how I would be able to check for that.

Perhaps there is a way to filter out all xml sitemaps from that list, but again, I don't know how.

Therefore I would suggest to simply add your own line of code to remove (display:none;) the warning from your admin to either your theme's functions.php file or a functionality plugin.

Hope this helps and sorry I cannot help you any further with this. You are more than welcome to dive further into this and if you find a way to filter for the xml-sitemap group, then I am more than willing to add that to my plugin.

Thanks,
Piet

**Comment by senlin** [comment]
The [Google Analytics plugin](https://wordpress.org/plugins/google-analytics-for-wordpress/) has been rebranded and taken over by [Syed Balkhi](https://syedbalkhi.com/), I would like to suggest to address any concerns to him directly as he seems quite responsive to improve the plugin and not harass its users.
