### ISSUE TITLE
make compatible to All in One SEO pack

### ISSUE THREAD

**Issue by TomasHurtz** [senlin/so-clean-up-wp-seo#60]
Hello - looks nice plugin - can you make for SEO All In One ?

This helps: https://gist.github.com/llgruff/a7ab776167aa0ed307ec445df54e5fdb

But still a lot of other bloat and also in sitemap

**Comment by senlin** [comment]
Hi Tomas, thanks for the suggestion, but not interested. Someone else can do that :)
