### ISSUE TITLE
Remove "Translate YOAST Seo Premium" nag box

### ISSUE THREAD

**Issue by allanrehhoff** [senlin/so-clean-up-wp-seo#62]
YOAST Seo Free contains advertisments for the premium version, and the premium version contains advertisments/callouts for translation help (though many plugins do that)

## Expected behavior
An option/checkbox that hides this box (see screenshot)

## Current behavior
The box seems to appear randomly, but contains a cartoon-ish logo that doesn't fit with the wordpress core design.

## How to replicate

1. Install Yoast SEO Premium
2. Install WPML
3. Set up Finnish language in WPML 
4. Navigate around in Seo Premium screens until the box appears.

It's likely that the box will also come with other languages that Yoast Premium isn't translated fully into yet.

## Possible way to add this
The advertisment has an ID attribute which can be used to hide it.

```
#i18n_promo_box {
	display: none!important;
}
```

## Screenshots
![2019-06-24_14-59-47](https://user-images.githubusercontent.com/24595705/60021327-18625580-9692-11e9-906e-2a95aae39c7f.png)

Edit: Fixed markdown formatting in list

**Comment by senlin** [comment]
Hi Allan,

Thanks for your ticket.

The thing is that for things like this to be implemented I'd need a premium license and I have no intention to send yoast money, so unless someone makes such a license available to me, it is not likely that I start including code that removes or hides garbage from the premium version of the yoast plugin.

Does that make sense?

**Comment by allanrehhoff** [comment]
That's totally understandable, I wouldn't send yoast money myself, if it wasn't for the client that I work with who required premmium version.

Anyway, feel free to close the issue if you do not plan on making any changes regarding to this, however, would it be ok if I made a PR somewhere in the future instead, any chance for that to get merged?
(Considering that I'd even get the time to do such thing)

**Comment by senlin** [comment]
Hi Allan,
I always welcome PRs, so if you find the time then surely I encourage you to submit one :)
Will close the issue for now, but you can re-open it once you want to re-visit it.
