### ISSUE TITLE
2 bugs and 1 feature request

### ISSUE THREAD

**Issue by Dibbyo456** [senlin/so-clean-up-wp-seo#64]
Currently if we hide Admin columns such as SEO score column, Readability score column etc the data actually gets hidden but the options still shows up "Screen Options" settings. I'm guessing the columns is not unhooking the proper way. The proper way to hide those would be this: https://gist.github.com/amboutwe/18558a7e681e36c6bfe6e4fb647265ce

“Remove HTML Comments” does not work on Yoast SEO Premium.
`<!-- / Yoast SEO Premium plugin. -->` still shows up in source code.
Proper way to hide this would be: https://buddydev.com/remove-this-site-is-optimized-with-the-yoast-seo-plugin-vx-y-z/

FR: is there any way to hide “Advanced” tab? – https://s.put.re/jPZh688X.png

**Comment by senlin** [comment]
@Dibbyo456 thanks for your message. Bit difficult to address 2 bugs and 1 feature request in one issue, so I split them up in 3 separate issues and closing this. Thanks for your understanding.
