### ISSUE TITLE
[Feature Request] Hide “Advanced” tab

### ISSUE THREAD

**Issue by senlin** [senlin/so-clean-up-wp-seo#67]
Originally reported by @Dibbyo456 as issue #64

Is there any way to hide “Advanced” tab? – https://s.put.re/jPZh688X.png

**Comment by Dibbyo456** [comment]
The proper way to hide this modify the function `get_seo_meta_section()` on `\wordpress-seo\admin\metabox\class-metabox.php` Line 330.

**Comment by Dibbyo456** [comment]
Another way would be:

````php
/**
 * Hide Advanced tab from Yoast meta.
 * Only affect post editor screen.
 */
add_action( 'current_screen', function() {
	if ( get_current_screen()->id == 'post' ) {
		add_filter( 'user_has_cap', function( $allcaps, $cap, $args ) {
			$allcaps['wpseo_manage_options'] = false;
			return $allcaps;
		}, 10, 3 );
	}
});
````

**Comment by senlin** [comment]
@Dibbyo456 thanks for this Feature Request. That function indeed does the trick.

I never felt the urge to remove the entire Advanced "tab", as it is closed by default anyways, but I can imagine that some people would like to remove as much as they can, and then this might be a useful option.

So I will add it to the plugin, but I will leave it visible by default, if only not to surprise people that actually are using the Advanced section of the metabox.

**Comment by Dibbyo456** [comment]
I think most users will prefer the "close advanced tab". I just wanted to get rid of it since I almost never uses it.

**Comment by senlin** [comment]
> I just wanted to get rid of it because I almost never uses it.

But for Pages and other CPTs you're fine that it is there? That is my issue with it. I can remove it from the post editor, but then what about the page editor and any other editor screens?

**Comment by Dibbyo456** [comment]
I like to have it enabled on pages because sometimes pages needs to be "noindex" or change "canonical" etc where "posts" does not need these options, because almost no user write a post and have it "noindex".

Not sure about custom post type, but I rarely use it.
Perhaps we can create an array of CPT and loop through them and remove it?

**Comment by senlin** [comment]
> Perhaps we can create an array of CPT and loop through them and remove it?

Happy to merge it if you can send me a PR or a snippet I can use :)

**Comment by Dibbyo456** [comment]
````php
/**
 * Hide Advanced tab from Yoast metabox.
 * Works on Post, Page as well as CPT.
 */
add_action( 'current_screen', function() {
	// create array of default post types.
	// not sure about pages, perhaps make it optional?
	$default_post_types = array( 'post', 'page' );
	// get the custom post types if available.
	$custom_post_types = get_post_types( array( '_builtin' => false ) );
	// merge them. no errors if no cpt found.
	$all_post_types = array_merge( $default_post_types, $custom_post_types );

	// if current edit screen belong to post types, then change capability.
	if ( in_array( get_current_screen()->id, $all_post_types ) ) {
		add_filter( 'user_has_cap', function( $allcaps, $cap, $args ) {
			$allcaps['wpseo_manage_options'] = false;
			return $allcaps;
		}, 10, 3 );
	}
});
````

**Comment by senlin** [comment]
Great thank you Harry! Yes, I think it would be a good idea to make it optional for pages, as you said yourself:

> I like to have it enabled on pages because sometimes pages needs to be "noindex" or change "canonical" etc

**Comment by senlin** [comment]
@Dibbyo456 
Harry, so do I just leave the `page` post-type out when `$default_post_types` is defined or do you have a better idea?

**Comment by Dibbyo456** [comment]
> Harry, so do I just leave the page post-type out when $default_post_types is defined or do you have a better idea?

Frankly leave the `page` out of it for now. Later if lot of users asks for it the we can make it optional by pushing a simple update.
