### ISSUE TITLE
Remove primary category feature does not work with Yoast Premium

### ISSUE THREAD

**Issue by Dibbyo456** [senlin/so-clean-up-wp-seo#68]
Even though the plugin has this:

````php
/**
 * at some point Yoast SEO has introduced "Primary Category Feature"
 * This function removes this "feature"
 *
 * @since v3.6.0
 */
public function so_cuws_remove_primary_category_feature() {
	if ( ! empty( $this->options['remove_primarycatfeat'] ) ) {
		add_filter( 'wpseo_primary_term_taxonomies', '__return_empty_array' );
	}
}
````

but that does not seem to work with Yoast Premium. But if I add
```php
add_filter( 'wpseo_primary_term_taxonomies', '__return_empty_array' );
```
to **functions.php** then it works fine..

**Comment by senlin** [comment]
@Dibbyo456 I'm not planning for the premium version of Yoast, simply because I do not have a license for premium and I am not planning to get one anytime soon.

Feel free to add that filter to your own functions file :)
