### ISSUE TITLE
Remove Search Console menu because it's discontinued

### ISSUE THREAD

**Issue by Dibbyo456** [senlin/so-clean-up-wp-seo#69]
Google has discontinued its Crawl Errors API so the Search Console page in Yoast is useless now.

````php
/**
 * Remove Search Console menu from Yoast.
 */
add_action( 'admin_menu', function() {
    remove_submenu_page( 'wpseo_dashboard', 'wpseo_search_console' );
}, 999 );
````

**Comment by senlin** [comment]
Thanks for the update @Dibbyo456, good that someone keeps an eye on the current situation :)

Will remove it in the next release
