### ISSUE TITLE
Page Analysis Disabled on Posts

### ISSUE THREAD

**Issue by jourdanritchey** [senlin/so-clean-up-wp-seo#7]
The "Page Analysis" tab in the Yoast SEO box that appears when editing posts displays "Page Analysis has been disabled." when activating SO Clean Up Yoast SEO. Is this intentional? Is there an option to selectively enable the "Page Analysis" tab?

Thanks!

**Comment by senlin** [comment]
The plugin indeed adds a filter that disables the page analysis as you can see [here](https://github.com/senlin/so-clean-up-wp-seo/blob/master/so-clean-up-wp-seo.php#L82).

I am planning a Settings page for [version 2.0.0](https://github.com/senlin/so-clean-up-wp-seo/milestones/version%202.0.0), until then I'm afraid it will remain disabled.
