### ISSUE TITLE
[Patched] Remove Warning message from permalink page

### ISSUE THREAD

**Issue by Dibbyo456** [senlin/so-clean-up-wp-seo#71]
Previously suggested on #58 

````php
/**
 * Remove any filter.
 * Source: https://gist.github.com/tripflex/c6518efc1753cf2392559866b4bd1a53#gistcomment-2823505
 */
if ( ! function_exists( 'remove_class_hook' ) ) {
	function remove_class_hook( $tag, $class_name = '', $method_name = '', $priority = 10 ) {
		global $wp_filter;
		$is_hook_removed = false;
		if ( ! empty( $wp_filter[ $tag ]->callbacks[ $priority ] ) ) {
			$methods     = wp_list_pluck( $wp_filter[ $tag ]->callbacks[ $priority ], 'function' );
			$found_hooks = ! empty( $methods ) ? wp_list_filter( $methods, array( 1 => $method_name ) ) : array();
			foreach( $found_hooks as $hook_key => $hook ) {
				if ( ! empty( $hook[0] ) && is_object( $hook[0] ) && get_class( $hook[0] ) === $class_name ) {
					$wp_filter[ $tag ]->remove_filter( $tag, $hook, $priority );
					$is_hook_removed = true;
				}
			}
		}
		return $is_hook_removed;
	}
}

/**
 * Remove the permalink notice action.
 * Uses @remove_class_hook.
 */
add_action( 'admin_init', function() {
	remove_class_hook( 'admin_notices', 'WPSEO_Admin_Init', 'permalink_settings_notice' );
});
````

This might help in future: https://harry.plus/blog/remove-any-action-filter-wordpress/

The warning message function located on `/admin/class-admin-init.php`

**Comment by senlin** [comment]
@Dibbyo456 
Very helpful patch and resources Harry, thank you for digging in! I will add this to the other patches/fixes.

**Comment by senlin** [comment]
@Dibbyo456 - Hi Harry, this function seems to cause issues after updating to WP 5.5

Please see #88 as well as https://wordpress.org/support/topic/fatal-error-with-wp-5-5-and-spcific-plugin/#post-13239538

**Comment by Dibbyo456** [comment]
Thanks for pinging. I haven’t tested anything on 5.5 but I’m looking into it.

**Comment by andreiglingeanu** [comment]
@Dibbyo456 @senlin Can be reproduced by putting this anywhere (`functions.php` of the active theme will do):


```php
add_action(
	'admin_notices',
	function () {
	}
);
```

**Comment by andreiglingeanu** [comment]
@senlin @Dibbyo456 just created a PR with the solution that seems fit [here](https://github.com/senlin/so-clean-up-wp-seo/pull/89). Will be happy to change it according to your remarks.

**Comment by Dibbyo456** [comment]
So, what exactly changed in wp 5.5 that’s breaking previous version?

**Comment by senlin** [comment]
> I will dig tomorrow

Yeah it is late here too, but thanks to @andreiglingeanu no more need to dig :)

**Comment by knutsp** [comment]
I can confirm that adding an action to 'admin_notices' using a closure, in any theme (it seems), triggers this fatal.

**Comment by Dibbyo456** [comment]
Can you reproduce it with 5.4?

**Comment by andreiglingeanu** [comment]
@Dibbyo456 No, can't reproduce with 5.4.

They introduced this `is_object()` check in 5.5: https://github.com/WordPress/WordPress/blob/dc63fb7c85598d1a0eb6b4000616bab052247837/wp-includes/class-wp-list-util.php#L113

[And a closure is indeed an object :/](https://share.getcloudapp.com/nOuk8Py8)
