### ISSUE TITLE
WP rocket conflict

### ISSUE THREAD

**Issue by alriksson** [senlin/so-clean-up-wp-seo#74]
The Hide SEO Bloat plugin prevents all the other optimizations (like cache busting, minification, and the insertion of the CPCSS) in WP Rocket from working — so I had to deactivate it.

Most likely, it’s using certain output buffer functions, which interfere with WP Rocket’s ability to generate its own buffer.

**Comment by senlin** [comment]
@alriksson thanks for posting

Not entirely sure though as the plugin works on the backend and therewith should have nothing to do with any of the things you mention?

What makes you think that this plugin is the culprit?

**Comment by alriksson** [comment]
Since WP rocket only works (like cache busting, minification, and the insertion of the CPCSS) once I disable `so-clean-up-wp-seo` Also got it confirmed from WP Rocket support.

So until this bug is fixed the plugin and wp rocket together can not be used.

**Comment by senlin** [comment]
Can you please point me to the thread where WP Rocket confirms "this bug"?

To be honest I really have no idea what this could be, so any additional information would be very welcome.

Also what I find a little strange is that with more than 10K active installs, we have plenty of users that also have WP Rocket installed and I have never received any conflict report, ever.

**Comment by alriksson** [comment]
Over email support with WP Rocket. Email them and ask for Shelley.

All I can say is it worked once your plugin was disabled and when I asked WP rocket support are you sure? They confirmed it on their installs as well that this plugin is causing the issue.


```
ACF Cleaner | Version 1.4.2 by 1n3JgKl9pQ6cUMrW
ACF Local JSON | Version 1.0.0 by David Browne
ACF Options Page Admin | Version 3.9.4 by John A. Huebner II
Advanced Custom Fields Multilingual | Version 1.4.0 by OnTheGoSystems
Advanced Custom Fields PRO | Version 5.8.5 by Elliot Condon
Asset CleanUp: Page Speed Booster | Version 1.3.4.6 by Gabriel Livan
Better Search Replace | Version 1.3.3 by Delicious Brains
Code Snippets | Version 2.13.3 by Code Snippets Pro
Custom Post Type UI | Version 1.6.2 by WebDevStudios
Duplicate Page | Version 4.0 by mndpsingh287
Hide My WP Ghost Lite | Version 3.4.01 by WPPlugins - WordPress Security Plugins
If Menu - Visibility control for menu items | Version 0.15 by Layered
jQuery Manager for WordPress | Version 1.10.4 by Remzi Cavdar
Oxygen | Version 3.0.1 by Soflyy
Redis Object Cache | Version 1.5.0 by Till Krüss
Safe SVG | Version 1.9.4 by Daryll Doyle
ShortPixel Adaptive Images | Version 1.4.0 by ShortPixel
ShortPixel Image Optimizer | Version 4.14.6 by ShortPixel
User Role Editor Pro | Version 4.52 by Vladimir Garagulia
WPML Multilingual CMS | Version 4.2.9 by OnTheGoSystems
WP Rocket | Version 3.4.0.5 by WP Media
WPvivid Backup Plugin | Version 0.9.26 by WPvivid Team
WPvivid Backup Pro | Version 1.9.0 by wpvivid.com
Yoast SEO | Version 12.3 by Team Yoast


```

**Comment by senlin** [comment]
Thanks.

> Most likely, it’s using certain output buffer functions

The thing is the plugin is not using anything like that. There is nothing to buffer.

I will look into it, but don't hold your breath.

**Comment by senlin** [comment]
The only thing happening on the frontend is this

https://github.com/senlin/so-clean-up-wp-seo/blob/develop/includes/class-so-clean-up-wp-seo.php#L229-L240

**Comment by alriksson** [comment]
It is strange then but thanks for looking into it. Maybe I can put you in contact with their support so we can have the conversation in a thread with all parties.

Nothing in WP rocket works when the plugin is activated:
- Defer
- Minify
- Generate CCSS

**Comment by senlin** [comment]
> Maybe I can put you in contact with their support so we can have the conversation in a thread with all parties.

Yes please. My email is my first name and then the website name .

**Comment by alriksson** [comment]
Let me email you trhought the contact form and I loop in WP rocket.

**Comment by senlin** [comment]
After some emailing back and forth, it turns out that the "issue" apparently is in the **OPTIONAL** removal of frontend HTML comments. 

The mere fact that this has not been reported before and that it is an optional setting, I have labelled this as `wontfix` for now, until someone is articulate and helpful enough to change my mind.
