### ISSUE TITLE
Seo score columns visible when saving posts using 'Quick edit'

### ISSUE THREAD

**Issue by allanrehhoff** [senlin/so-clean-up-wp-seo#75]
The WPSEO score columns becomes visible once the 'Quick edit' feature is used to edit posts (probably also other CPT's)

Possibly a bug that has been introduced with [issue #65 ](https://github.com/senlin/so-clean-up-wp-seo/issues/65)

## Expected behavior
The columns are still hidden after hitting save.

## Current behavior
The columns are hidden when you enter the page, but becomes visible when posts are saved by using 'quick edit' feature.

## Possible solution
It's possible that there is a PHP fix for this behaviour too, I haven't had the time to dig into this issue yet.

But I found a quick workaround, simply hiding all columns starting with 'wpseo-' seems to fix the issue.

`.wp-list-table td[class^="wpseo-"] {
  display: none;
}`

## Steps to reproduce (for bugs)
1. Log in to wordpress and go to posts screen
2. Click the "Quick edit" link when hovering an item.
3. Click save
4. Additional columns should now appear

## Screenshots
![2019-11-07_15-55-12](https://user-images.githubusercontent.com/24595705/68400968-38923d00-0179-11ea-9656-e35ae2a10673.png)

**Comment by senlin** [comment]
Hi Allan, thanks for the report, I will ask @Dibbyo456 to have a look at this to see if he can fix this. If not then I agree that we will revert back to the old fashioned method of hiding (with CSS) instead of removing.

**Comment by Dibbyo456** [comment]
Nice catch. Unfortunately I’m on vacation and will get home a week later. I didn’t bring my laptop unfortunately.
I will take a look once I get home.

**Comment by senlin** [comment]
Hi @Dibbyo456 - thanks for getting back.

No worries, enjoy your holiday and once you're back it would be great if you can have a look then. I assigned this issue to you :)

**Comment by allanrehhoff** [comment]
> 
> 
> Hi Allan, thanks for the report, I will ask @Dibbyo456 to have a look at this to see if he can fix this. If not then I agree that we will revert back to the old fashioned method of hiding (with CSS) instead of removing.

I think removing it would be preferable in any case.

If @Dibbyo456 is unable to come up with a solution for this, you could just include my above fix/workaround as a fallback.

Since it's a one-liner CSS I don't think it'd cause too much of a performance penalty to the browser.

**Comment by Dibbyo456** [comment]
This is happening because when we're using Quick Edit, wp using admin_ajax.php to send and receive data, thus the filters not applying.

There are 2 possible options, either use the old css method, or I need to figure out a way to filter the ajax response.

**Comment by senlin** [comment]
Thanks for looking into it @Dibbyo456 

> or I need to figure out a way to filter the ajax response

yes please :)

**Comment by Dibbyo456** [comment]
Unfortunately I could not find anything that would fix the issue. I leaving you to decide what to do. 😞

**Comment by senlin** [comment]
Thanks for checking, I will place back the original CSS then.

**Comment by senlin** [comment]
fixed in new release which will go live on WP in a minute
