### ISSUE TITLE
SEO Premium upsell notice has a new class name.

### ISSUE THREAD

**Issue by allanrehhoff** [senlin/so-clean-up-wp-seo#76]
The yoast SEO admin block upsell notice seems to have gotten a new class name, resulting in the "Premium Upsell Admin Block" setting no longer having an effect.

## Expected behavior
the upsell notice (shown in screenshot) hidden.

## Current behavior
WordPress version 5.3, Yoast Free Version 12.5 and Hide SEO Bloat Version 3.13.1, shows the ad shown in screenshot, with the 'Premium Upsell Admin Block' setting enabled in "SO Hide Seo Bloat"

## Possible solution
Slight change required in this setting.

**File**
class-so-clean-up-wp-seo.php:409

**Change to**
`echo '.yoast_premium_upsell,.yoast_premium_upsell_admin_block,#wpseo-local-seo-upsell{display:none}'; // @since v3.1.0; @modified v3.13.X`

(I know modifying plugin files is discouraged) But doing this fixed this issue for me.

## Context
In the General tab of Yoast SEO admin page.

## Screenshots
![2019-11-19_11-17-04](https://user-images.githubusercontent.com/24595705/69138631-4d4acb00-0abf-11ea-99e9-b39c21b7cac0.png)

**Comment by senlin** [comment]
Thanks for the report Allan @allanrehhoff ! Will add that to the next version, which will come out soon.

**Comment by senlin** [comment]
fixed in new release which will go live on WP in a minute
