### ISSUE TITLE
Option to hide "Help beacon", new "feature" added in yoast seo.

### ISSUE THREAD

**Issue by allanrehhoff** [senlin/so-clean-up-wp-seo#77]
The latest version of Yoast SEO (Version 12.6.1 ) added a new "feature" or addition to their help center options.

Sorry for creating all these issues lately, but I swear with every update the Yoast Team adds another ad, or "feature". Let me know If I should slow down on bug reports/feature requests.

## Possible way to fix this
Add an option to the "Help center" section of this plugin, that allows the user to also hide the "Help beacon". I'd recommend having this option enabled by default.

## Screenshots
![2019-11-27_11-09-57](https://user-images.githubusercontent.com/24595705/69714859-83afc800-1107-11ea-84ee-161a69dd954f.png)

**Comment by allanrehhoff** [comment]
Just found that this button/section can be found using the following CSS

`/** Hide the "Help beacon" */
#yoast-helpscout-beacon {
	display: none;
}`

**Comment by senlin** [comment]
Hi Allan,

Thanks for showing this new issue! Not a problem at all that you're opening issues, it is quite obvious that I simply cannot keep up with the release schedule of Yoast!

Just to clarify 

> I'd recommend having this option enabled by default.

With this you mean you would expect the help beacon to be hidden by default, correct?

Hopefully over the weekend I can come with an update, many thanks for already providing the CSS!

**Comment by allanrehhoff** [comment]
> Hi Allan,
> 
> Just to clarify
> 
> > I'd recommend having this option enabled by default.
> 
> With this you mean you would expect the help beacon to be hidden by default, correct?

Yes that is what I meant. English isn't my main language, so translation issues can happen.

Thanks for looking into it.

**Comment by senlin** [comment]
@allanrehhoff 

Hi Allan, happy new year!
Sorry for the late commit, but better late than never, right?
The new release will soon be available in the WP Repo too.
Cheers,
Pieter
