### ISSUE TITLE
Help Beacon, got a new class and is now more invasive.

### ISSUE THREAD

**Issue by allanrehhoff** [senlin/so-clean-up-wp-seo#79]
Team YOAST is at it again, adding more unwanted and invasive "features"

The help beacon has gotten a new class in one of the recent versions of YOAST Seo, which creates another "popup" and in some cases even hinder the use of their "Redirects" tool (Part of Premium version)

See issue #77 for reference.

## Expected behavior
The help beacon is hidden.

## Current behavior
The beacon pops up with a "Need some help" screen (See screenshot), first time the page is visited, after that only the ugly '?' icon stays visible.

## Possible solution
The fix for this is easy though,
All that needs to be added is the selector `#beacon-container,`
to `includes/class-so-clean-up-wp-seo.php:501`

## Steps to reproduce (for bugs)
Appears on almost any YOAST Seo screen in newest version.

## Screenshots
![2020-01-30_10-31-25](https://user-images.githubusercontent.com/24595705/73437539-d5b1db80-434c-11ea-9f2d-cffa2b536826.png)

**Comment by senlin** [comment]
@allanrehhoff 
Hi Allan, thanks for the report. I tried replicating it on my dev install, but cannot see anything. At first I thought it had to do with the fact that the site was running on ClassicPress and it seems that Yoast is now fully incompatible with that, but even after switching back to WP, the big questionmark only becomes visible when I deactivate the Hide SEO Bloat plugin. And the new popup I cannot see at all.

**Comment by allanrehhoff** [comment]
Hi Peter.

Did some further investigation, it turns out that this popup is a "premium feature" (I'm at a loss of words here...)

The help beacon is in fact hidden in the regular versions of YOAST Seo, but has this other class name in the permium version.

Though I have tested the above fix, so if you're willing to take my word for it, you should be able to safely add it to the next update.

Otherwise feel free to do with this issue as you please :)

**Comment by senlin** [comment]
Hi Allan, I do take your word for it, but to be honest I am not going to add things that only exist in the premium version of the plugin, that simply does not make sense for me.
So I will indeed close it, sorry for that, but at least it is documented for if others run into it.
Thanks for reporting it nevertheless!
Pieter
