### ISSUE TITLE
yoast translate promo box

### ISSUE THREAD

**Issue by tkes** [senlin/so-clean-up-wp-seo#8]
Can you add removal of yoast translate promo box `<div id="i18n_promo_box"..` as well?

Thanks for the plugin.

**Comment by senlin** [comment]
Similar as your other question, we will address this once we have rebuild the plugin with a Settings page. Explanation in the plugin file: https://github.com/senlin/so-clean-up-wp-seo/blob/master/so-clean-up-wp-seo.php#L90

**Comment by senlin** [comment]
Can anyone check whether this promotion box still exist? I cannot find it anymore.

**Comment by senlin** [comment]
no response, so I'm closing this out. if it pops up again, feel free to re-open this issue.
