### ISSUE TITLE
Plugin negates plugin updates

### ISSUE THREAD

**Issue by or128** [senlin/so-clean-up-wp-seo#81]
Hello,
While this plugin is enabled I do not see any plugin updates offered up at the plugins interface.
After disabling it, the plugins suddenly have uptakes available.

I am not sure what more information I could give.
Before the latest version was released the plugin just somehow canceled the red budge on the plugin menu item, but after the recent update having it enabled completely blocks updated from appearing. 

Thank you

**Comment by senlin** [comment]
Can you please send a before/after screenshot so I know where to look?

**Comment by or128** [comment]
I am not sure how to comply with your request.
If the plugin is active I will not see that there are updates for plugin.
After I disable it, suddenly the plugins interface show that plugins have updates.
The plugin also hides the budge that appears on the plugins menu item and is suppose to notify you that updates are available.

**Comment by senlin** [comment]
> The plugin also hides the badge that appears on the plugins menu item and is suppose to notify you that updates are available.

Okay, this one I indeed see happening now, that is strange and I will fix that soon

> If the plugin is active I will not see that there are updates for plugin.

This one I cannot replicate, see this screenshot where you can clearly see that there are updates available.

![screenshot](https://monosnap.com/image/JwertMO66hjlvAbjfgJ9j1rRGJJkk2)

**Comment by or128** [comment]
I see, let me test a bit more for a few days, but it's good you can fix the first issue. thanks.

**Comment by or128** [comment]
You are correct, there in no issue.

**Comment by senlin** [comment]
Just released new version that fixes this issue, thanks for reporting.
