### ISSUE TITLE
Hidden SEO columns reappear after quick-edit & break column layout

### ISSUE THREAD

**Issue by Emanuel-23** [senlin/so-clean-up-wp-seo#93]
When using "quick edit" in a post types list view with enabled setting for hiding the SEO columns in lists, the hidden columns reappear after you have clicked "save". 
The output of such columns will contain random data (maybe some kind of raw data). Moreover the layout will break until you refresh the site, because the column `<td>` elements will be added but not their corresponding `<th>`, so the columns will not match and end in a strange layout.

## Expected behavior

The hidden columns wont appear, when using the quick edit function.

## Current behavior

See description above.

## Possible solution

Unfortunately I didnt have time so far, to deeply investigate the reasons... Just wanted to report it at first.

## Steps to reproduce (for bugs)

1. Open a post types list in admin (i.e. `wp-admin/edit.php`) 
2. if there is no post  yet, create one and return to the list
3. hover over one element in the list and click on "quick edit"
4. change something
5. save
6. see the issue

## Context

- so-clean-up-wp-seo v3.14.4
- Wordpress v5.6.0
- Wordpress has been set up with [roots/bedrock](https://github.com/roots/bedrock)
- YOAST SEO v15.5

## Screenshots

![issue](https://user-images.githubusercontent.com/48509424/102895422-f43d2b80-4464-11eb-9de8-bd1338ee83f8.png)

**Comment by senlin** [comment]
Hi Emanuel,
Many thanks for your detailed report.
I will need some time to investigate this too, which I can do in the next few days.
If you discover something in the meantime, please update this ticket accordingly.
Thanks,
Pieter

**Comment by senlin** [comment]
@Emanuel-23 
I tried reproducing this on one of my sandbox site, but I cannot.
Could it be related to the theme you're using on that site or perhaps a conflict with another plugin?

**Comment by Emanuel-23** [comment]
sorry to be late on this.

I use `roots/bedrock` (wordpress boilerplate) with `roots/sage` (starter theme), see https://roots.io/ for more information.
Note that the theme I use, is NOT the well documented version 9 but the version 10 which itself depends on roots/acorn, see https://github.com/roots/sage. 
Id suggest you to give it a try (anyways), because thats a stack one can work with when developing on wordpress. but thats just a side note and my opinion of course.

I didn't find time to investigate it any further. I try to dig deeper as soon as i find time.

**Comment by senlin** [comment]
Thanks for the tip on roots! I will close this issue now, but feel free to re-open it if you have found the culprit.
