### ISSUE TITLE
Option to hide Cornerstone Content filter

### ISSUE THREAD

**Issue by chrisvanpatten** [senlin/so-clean-up-wp-seo#99]
It'd be great to have a checkbox option (likely off by default) to hide the Cornerstone Content filter link on list tables.

## Expected behavior
n/a

## Current behavior
n/a

## Possible way to add this
A checkbox!

## Screenshots
<img width="426" alt="Screen Shot 2021-04-23 at 10 56 56 AM" src="https://user-images.githubusercontent.com/1231306/115890270-c374ff00-a422-11eb-8435-82edc75c8251.png">

**Comment by senlin** [comment]
Hi Chris,
Thanks for the suggestion.
Doesn't Yoast already come with that option in the settings?
https://yoast.com/help/disable-cornerstone-content/

**Comment by chrisvanpatten** [comment]
@senlin Sure enough, totally missed that. Thanks!
